# Generated by Django 5.1.15 on 2026-06-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_remove_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'stock movement', 'verbose_name_plural': 'stock movements'},
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='quantity',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='on_hand_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='on_hand_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='on_hand_delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reserved_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reserved_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reserved_delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('delivery', 'Delivery'), ('reservation', 'Reservation'), ('release', 'Release'), ('adjustment', 'Adjustment')], max_length=32),
        ),
    ]
