# Generated by Django 5.1.15 on 2026-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_immutable_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='inventory_s_referen_5aaa1a_idx',
            old_name='inv_stock_referenc_3b6e5d_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='inventory_s_product_5919a9_idx',
            old_name='inv_stock_product_6d7bbf_idx',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('delivery', 'Delivery'), ('reservation', 'Reservation'), ('release', 'Release'), ('adjustment', 'Adjustment'), ('consumption', 'Consumption'), ('production', 'Production')], max_length=32),
        ),
    ]
