# Generated by Django 5.1.15 on 2026-06-21 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0006_manufacturingorder_source_manufacturing_order'),
        ('purchases', '0005_purchaseorder_assignee_purchaseorder_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='source_manufacturing_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_purchase_orders', to='manufacturing.manufacturingorder'),
        ),
    ]
