# Generated by Django 5.1.15 on 2026-06-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_userprofile_avatar_public_id_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role_title',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
