export type { Icon as AppIcon } from "react-bootstrap-icons";
export type { Icon as LucideIcon } from "react-bootstrap-icons";

export {
  Activity,
  ArrowDown,
  ArrowDownUp,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  Bell,
  BoxArrowRight,
  Boxes,
  Camera,
  ChevronLeft,
  ChevronRight,
  Clock,
  Command,
  Envelope,
  Envelope as Mail,
  Eye,
  EyeSlash,
  Funnel as Filter,
  Inbox,
  Lock,
  Moon,
  Play,
  Plus,
  QrCode,
  Search,
  ShieldCheck,
  Star,
  Sun,
  Trash as Trash2,
  Truck,
  UpcScan as ScanLine,
  Wrench
} from "react-bootstrap-icons";

export {
  ExclamationCircle as AlertCircle,
  ExclamationTriangle as AlertTriangle,
  ExclamationTriangle as ShieldAlert,
  ExclamationTriangle as TriangleAlert,
  BarChart as BarChart3,
  Robot as Bot,
  CheckCircle as CheckCircle2,
  ClipboardCheck as ClipboardList,
  CurrencyDollar as DollarSign,
  BuildingGear as Factory,
  ClockHistory as FileClock,
  Diagram3 as GitBranch,
  Speedometer2 as Gauge,
  House as Home,
  QuestionCircle as HelpCircle,
  InfoCircle as Info,
  List as Menu,
  BoxSeam as Package,
  BoxSeam as PackageCheck,
  BoxSeam as PackageSearch,
  People as Users,
  Receipt as ReceiptText,
  SignpostSplit as Route,
  Gear as Settings,
  Cart as ShoppingCart,
  Stopwatch as Timer,
  GraphUpArrow as TrendingUp,
  Wallet2 as WalletCards,
  HouseDoor as Warehouse
} from "react-bootstrap-icons";

export { ArrowRepeat, ArrowRepeat as Loader2 } from "react-bootstrap-icons";
