# Generated by Django 5.1.15 on 2026-06-20 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('backend_type', models.CharField(choices=[('auto', 'Auto-detect'), ('django', 'Django / DRF'), ('fastapi', 'FastAPI')], default='auto', max_length=20)),
                ('base_url', models.URLField(blank=True, default='')),
                ('schema_url', models.URLField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('auth_header_prefix', models.CharField(default='Bearer', max_length=20)),
                ('extra_headers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_dashboard_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndpointSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('method', models.CharField(max_length=16)),
                ('module', models.CharField(blank=True, default='', max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('operation_id', models.CharField(blank=True, default='', max_length=255)),
                ('auth_required', models.BooleanField(default=False)),
                ('request_schema', models.JSONField(blank=True, default=dict)),
                ('response_schema', models.JSONField(blank=True, default=dict)),
                ('last_discovered_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='api_dashboard.dashboardprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='all', max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('total_endpoints', models.PositiveIntegerField(default=0)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('successful_tests', models.PositiveIntegerField(default=0)),
                ('failed_tests', models.PositiveIntegerField(default=0)),
                ('skipped_tests', models.PositiveIntegerField(default=0)),
                ('average_response_ms', models.FloatField(default=0)),
                ('success_rate', models.FloatField(default=0)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api_dashboard.dashboardprofile')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_dashboard_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('method', models.CharField(max_length=16)),
                ('test_type', models.CharField(choices=[('connectivity', 'Connectivity'), ('auth', 'Authentication'), ('authorized', 'Authorized'), ('validation', 'Validation'), ('performance', 'Performance')], max_length=20)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('skip', 'Skip'), ('warn', 'Warn')], max_length=20)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_time_ms', models.FloatField(default=0)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('stack_trace', models.TextField(blank=True, default='')),
                ('validation_errors', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='api_dashboard.endpointsnapshot')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api_dashboard.testrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='endpointsnapshot',
            index=models.Index(fields=['profile', 'module'], name='api_dashboa_profile_23b0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointsnapshot',
            index=models.Index(fields=['profile', 'auth_required'], name='api_dashboa_profile_920ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointsnapshot',
            index=models.Index(fields=['profile', 'active'], name='api_dashboa_profile_b44675_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='endpointsnapshot',
            unique_together={('profile', 'path', 'method')},
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['run', 'status'], name='api_dashboa_run_id_847219_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['run', 'test_type'], name='api_dashboa_run_id_899fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['path', 'method'], name='api_dashboa_path_c8c550_idx'),
        ),
    ]
