# Generated by Django 5.1.15 on 2026-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_manufacturing_execution_and_procurement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('done', 'Done'), ('to_close', 'To Close'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
    ]
