# Generated by Django 5.1.15 on 2026-06-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_manufacturingorder_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
        ),
    ]
