# Generated by Django 5.1.15 on 2026-06-21 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_billofmaterial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='source_manufacturing_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_manufacturing_orders', to='manufacturing.manufacturingorder'),
        ),
    ]
